INSERT INTO `jobs` (name, label) VALUES
  ('offpolice','Poza służbą'),
  ('offambulance','Poza służbą'),
  ('offmecano','Poza służbą')
;

INSERT INTO `job_grades` (job_name, grade, name, label, salary, skin_male, skin_female) VALUES
	('offpolice',0,'kadet','Kadet',700,'{}','{}'),
	('offpolice',1,'oficer','Oficer I',900,'{}','{}'),
	('offpolice',2,'oficer-','Oficer II',1200,'{}','{}'),
	('offpolice',3,'oficer+','Oficer III',1400,'{}','{}'),
	('offpolice',4,'oficer-+','Oficer III+I',1700,'{}','{}'),
	('offpolice',5,'sierzant','Sierzant I',2200,'{}','{}'),
	('offpolice',6,'sierzant-','Sierzant II',2700,'{}','{}'),
	('offpolice',7,'porucznik+','Porucznik I',2900,'{}','{}'),
	('offpolice',8,'porucznik-','Porucznik II',3200,'{}','{}'),
	('offpolice',9,'kapitan','Kapitan I',3500,'{}','{}'),
	('offpolice',10,'kapitan-','Kapitan II',3700,'{}','{}'),
	('offpolice',11,'kapitan+','Kapitan III',3900,'{}','{}'),
	('offpolice',12,'boss','Komendant',4200,'{}','{}'),
	('offpolice',13,'boss','Zast. Szefa',4700,'{}','{}'),
	('offpolice',14,'boss','Asyst. Szefa',5200,'{}','{}'),
	('offpolice',15,'boss','Szef Policji',5700,'{}','{}'),
	('offambulance',0,'praktykant','Praktykant',700,'{}'),
	('offambulance',1,'pielegniarz','Pielegniarz',900,'{}'),
	('offambulance',2,'ratmed','Ratownik Medyczny',1100,'{}'),
	('offambulance',3,'lekarz','Lekarz',1500,'{}'),
	('offambulance',4,'slekarz','Starszy Lekarz',1700,'{}'),
	('offambulance',5,'doktor','Doktor',2200,'{}'),
	('offambulance',6,'sdoktor','Starszy Doktor',2700,'{}'),
	('offambulance',7,'specjalista','Specjalista',2950,'{}'),
	('offambulance',8,'sspecjalista','Starszy Specjalista',3200,'{}'),
	('offambulance',9,'chirurg','Chirurg',3700,'{}'),
	('offambulance',10,'profesor','Profesor',4200,'{}'),
	('offambulance',11,'boss','Profesor (Zarząd)',4450,'{}'),
	('offambulance',12,'boss','Ordynator',4700,'{}'),
	('offambulance',13,'boss','Zast. Dyrektora (Zarząd)',5200,'{}'),
	('offambulance',14,'boss','Asyst. Dyrektora',5700,'{}'),
	('offambulance',15,'boss','Dyrektor Szpitala',6200,'{}'),
	('offmecano',0,'rekrut','Rekrut',1700,'{}','{}'),
	('offmecano',1,'mlodszym','Mlodszy Mechanik',1950,'{}','{}'),
	('offmecano',2,'mechanik','Mechanik',2200,'{}','{}'),
	('offmecano',3,'smechanik',"Starszy Mechanik",2450,'{}','{}'),
	('offmecano',4,'fachowiec','Fachowiec',2700,'{}','{}'),
	('offmecano',5,'majster','Majster',2950,'{}','{}'),
	('offmecano',6,'boss','Menadzer Mechanikow',3200,'{}','{}'),
	('offmecano',7,'boss',"Zast. Szefa",3700,'{}','{}'),
	('offmecano',8,'boss','Asyst. Szefa',4200,'{}','{}'),
	('offmecano',9,'boss','Szef LSC',4700,'{}','{}')
;